# Generated by Django 6.0.3 on 2026-03-14 15:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('zona', models.CharField(choices=[('sotano', 'Sotano'), ('primer_piso', 'Primer piso'), ('segundo_piso', 'Segundo piso'), ('exterior', 'Exterior')], default='primer_piso', max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('reservado', models.BooleanField(default=False)),
                ('observacion', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Cupo',
                'verbose_name_plural': 'Cupos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('tipo_vehiculo', models.CharField(max_length=30)),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_fraccion', models.DecimalField(decimal_places=2, help_text='Cobro base para periodos menores a una hora.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'ordering': ['tipo_vehiculo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('automovil', 'Automovil'), ('moto', 'Moto'), ('camioneta', 'Camioneta'), ('bicicleta', 'Bicicleta')], max_length=20)),
                ('propietario', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado')], default='activo', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=160)),
                ('cupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.cupo')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.tarifa')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.vehiculo')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha_entrada'],
            },
        ),
    ]
